version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: "1111"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_db_vol:/var/lib/postgresql/data
    restart: unless-stopped

  resource-svc:
    build:
      context: ./resource-svc
      dockerfile: Dockerfile
    image: resource-svc
    container_name: resource-svc
    environment:
      DB_HOST: "postgres"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "1111"
      SONG_SVC: "song-svc"
    ports:
      - "8071:8071"
    depends_on:
      - postgres
    restart: unless-stopped

  song-svc:
    build:
      context: ./song-svc
      dockerfile: Dockerfile
    image: song-svc
    container_name: song-svc
    environment:
      DB_HOST: "postgres"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "1111"
    ports:
      - "8072:8072"
    depends_on:
      - postgres
    restart: unless-stopped