version: '3'
services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_db_vol:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    restart: unless-stopped

  resource-svc:
    build:
      context: ./resource-svc
      dockerfile: Dockerfile
    image: resource-svc
    container_name: resource-svc
    environment:
      DB_HOST: ${DB_HOST}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SONG_SVC: "song-svc"
    ports:
      - "8071:8071"
    depends_on:
      - postgres
      - song-svc
    restart: unless-stopped

  song-svc:
    build:
      context: ./song-svc
      dockerfile: Dockerfile
    image: song-svc
    container_name: song-svc
    environment:
      DB_HOST: ${DB_HOST}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8072:8072"
    depends_on:
      - postgres
    restart: unless-stopped